import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useAuth } from "@clerk/nextjs";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFire } from "@fortawesome/free-solid-svg-icons";
import * as React from "react";
import Calendar from "../components/Calendar";
import { PageLayout } from "../components/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vocabulary learning App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div style={{ backgroundColor: "#11151C" }} className="py-28 ">
          <div className=" tracking-tightsm:text-[5rem] container flex flex-wrap  items-center justify-start gap-2 px-6 pt-3 text-4xl font-extrabold text-white">
            <h2>Welcome </h2>
            <span className="text-[#f49943]">X</span>
            <span className="py-3">
              Great job, you&apos;ve been on strike for
            </span>
            <span className=" text-5xl text-[#f49943] ">11</span>
            <FontAwesomeIcon
              icon={faFire}
              className="text-5xl"
              style={{ color: "#f49943" }}
            />
            <span className="pt-3">days</span>
            <Calendar />
            <AuthShowcase />
          </div>
        </div>
      </PageLayout>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { isSignedIn } = useAuth();
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined,
    { enabled: !!isSignedIn },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {isSignedIn && (
        <>
          <p className="text-center text-2xl text-white">
            {secretMessage && (
              <span>
                {" "}
                {secretMessage} click the user button!
                <br />
              </span>
            )}
          </p>
        </>
      )}
    </div>
  );
};
